org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

android.injected.signing.store.file=/Users/macmini/Documents/key.jks
android.injected.signing.store.password=on5laught
android.injected.signing.key.alias=key
android.injected.signing.key.password=on5laught