// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDey4S6cYDpwf7Oa9xmo9MeaC7R8fT9MA',
    appId: '1:839020272136:web:2651b56600fdaa4f630fbd',
    messagingSenderId: '839020272136',
    projectId: 'sip-bn-666',
    authDomain: 'sip-bn-666.firebaseapp.com',
    storageBucket: 'sip-bn-666.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbRjC8I8_dr6jOvfDmDvTK0tPxgJ451-M',
    appId: '1:839020272136:android:149da53a5dc86344630fbd',
    messagingSenderId: '839020272136',
    projectId: 'sip-bn-666',
    storageBucket: 'sip-bn-666.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8dxHft859gGAuxxKPnwkvmHgRQww3iLw',
    appId: '1:839020272136:ios:315504e4d31df36a630fbd',
    messagingSenderId: '839020272136',
    projectId: 'sip-bn-666',
    storageBucket: 'sip-bn-666.firebasestorage.app',
    iosBundleId: 'com.smkbaknus666.sip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8dxHft859gGAuxxKPnwkvmHgRQww3iLw',
    appId: '1:839020272136:ios:315504e4d31df36a630fbd',
    messagingSenderId: '839020272136',
    projectId: 'sip-bn-666',
    storageBucket: 'sip-bn-666.firebasestorage.app',
    iosBundleId: 'com.smkbaknus666.sip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDey4S6cYDpwf7Oa9xmo9MeaC7R8fT9MA',
    appId: '1:839020272136:web:89332fa00cb63856630fbd',
    messagingSenderId: '839020272136',
    projectId: 'sip-bn-666',
    authDomain: 'sip-bn-666.firebaseapp.com',
    storageBucket: 'sip-bn-666.firebasestorage.app',
  );
}
